courses_login/apps/course_bot/urls.py
from django.conf.urls import url
from . import views
# from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^confirm/(?P<id>\d+)$', views.confirm, name='confirm'),
    url(r'^destroy/(?P<id>\d+)$', views.destroy, name='destroy'),
    url(r'^add_user_to_course$', views.users_courses, name='add_page'),
    url(r'^add_user$', views.add_user, name='add_user'),
]

courses_login/apps/login_registration/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^process$', views.process, name='process'),
    url(r'^success$', views.success, name='success'),
    url(r'^login$', views.login),
    url(r'^logoff$', views.clear)
]

courses_login/courses/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include("apps.course_bot.urls", namespace='course_bot')),
    url(r'^adduser/', include("apps.login_registration.urls", namespace='login_reg'))
]

courses_login/apps/course_bot/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_registration.models import User

class Course(models.Model):
    course_name = models.CharField(max_length = 50)
    description = models.CharField(max_length = 100)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    attendee = models.ManyToManyField(User, related_name='courses')

courses_login/apps/login_registration/models.py
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    email = models.CharField(max_length = 50)
    password = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

courses_login/apps/course_bot/views.py
from django.shortcuts import render, redirect
from .models import Course, User

def index(request):
    context = {
        'Courses': Course.objects.all(),
    }

    return render(request, 'course_bot/index.html', context)

def add(request):
    course_name = request.POST['name']
    description = request.POST['description']
    Course.objects.create(course_name=course_name, description=description)

    return redirect('index')

def confirm(request, id):
    context = {
        'Course': Course.objects.all().filter(id=id),
    }

    return render(request,'course_bot/destroy.html', context)

def destroy(request, id):
    Course.objects.filter(id=id).delete()
    
    return redirect('index')

def users_courses(request):
    context = {
        'users': User.objects.all(),
        'courses': Course.objects.all()
    }
    return render(request, 'course_bot/user_course.html', context)

def add_user(request):
    user = User.objects.get(id=request.POST['user_id'])
    course = Course.objects.get(id=request.POST['course_id'])
    course.attendee.add(user)
    return redirect('course_bot:add_page')

courses_login/apps/login_registration/views.py
from django.shortcuts import render, redirect
from .models import User
import re
import bcrypt
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
import hashlib


EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your views here.
def index(request):
    return render(request, "login_registration/index.html")

def process(request):
    errors = []
    user = User.objects.filter(email=request.POST['email'])


    if not request.POST['email']:
        errors.append("Email cannot be blank.")
    elif not EMAIL_REGEX.match(request.POST['email']):
        errors.append("Must be a valid email.")
    elif user:
        errors.append('Email is already in use.')

    if not request.POST['first_name']:
        errors.append("First name cannot not not be blank.")
    elif not request.POST['last_name']:
        errors.append("Last name cannot not not be blank.")

    if not request.POST['password']:
        errors.append("Password cannot not not be blank.")
    elif len(request.POST['password']) < 8:
        errors.append("Password must be at least 8 characters.")
    elif request.POST['password'] != request.POST['confirm']:
        errors.append('Password and confirm password must match.')

    if errors:
        for error in errors:
            messages.error(request, error)
        return redirect('/')
    else:
        User.objects.create(email=request.POST['email'], first_name=request.POST['first_name'], last_name=request.POST['last_name'], password=bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt()))
        user_id = User.objects.filter(email=request.POST['email'])[0].id
        request.session['user_id'] = user_id

        return redirect('login_reg:success')

def login(request):
    errors = []
    user = User.objects.all().filter(email=request.POST['email'])

    if not user:
        errors.append("Invalid login.")

    if errors:
        for error in errors:
            messages.error(request, error)
            return redirect('/')

    if bcrypt.checkpw(request.POST['password'].encode(), user[0].password.encode()):
        request.session["user_id"] = User.objects.get(email=request.POST['email']).id
        return redirect("/success")
    else:
        errors.append("Invalid login.")

    if errors:
        for error in errors:
            messages.error(request, error)
            return redirect('/')

def success(request):
    if "user_id" not in request.session:
        return redirect("/")
    name = User.objects.all().filter(id = request.session['user_id'])
    context = {

        'first_name': name[0].first_name
    }
    return render(request, "login_registration/success.html", context)

def clear(request):
    request.session.clear()
    return redirect('/')

courses_login/apps/login_registration/templates/login_registration/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Registration</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login_reg_db/styles.css' %}">
</head>
<body>
    <div id="wrapper">
        {% if messages %}
        {% for message in messages %}
        <p> {{ message }}</p>
        {% endfor %}
        {% endif %}
        <h1>Login</h1>
        <form action="/login" id="login" method='post'>
            {% csrf_token %}
            <div id="labels">
                <p>Email:</p>
                <p>Password:</p>
            </div>
            <div id="labelforms">
                <input type="text" name="email">
                <input type="password" name="password">
            </div>
        </form>
        <button type="submit" form="login">Submit</button>
        <h1>Registration</h1>
        <form action="{% url 'login_reg:process' %}" id="register" method='post'>
            {% csrf_token %}
            <div id="labels">
                <p>Email:</p>
                <p>First Name:</p>
                <p>Last Name:</p>
                <!-- <p>Birthdate (mm/dd/yyyy):</p> -->
                <p>Password:</p>
                <p>Confirm Password:</p>
            </div>
            <div id="labelforms">
                <input type="text" name="email">
                <input type="text" name="first_name">
                <input type="text" name="last_name">
                <!-- <input type="text" name="birthdate"> -->
                <input type="password" name="password">
                <input type="password" name="confirm">
            </div>
        </form>
        <button type="submit" form="register">Submit</button>
    </div><!-- /#wrapper  -->
</body>
</html>

courses_login/apps/login_registration/templates/login_registration/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>
    <h1>Success</h1>
    <h3>Hello, {{ first_name }}</h3>
    <form action="/logoff">
        <input type="submit" value="Log Off">
    </form>
</body>
</html>