restful_products/apps/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^show/(?P<id>\d+)$', views.show, name='show'),
  url(r'^edit/(?P<id>\d+)$', views.edit, name='edit'),
  url(r'^new$', views.new, name='new'),
  url(r'^create$', views.create, name='create'),
  url(r'^update/(?P<id>\d+)$', views.update, name='update'),
  url(r'^destroy/(?P<id>\d+)$', views.destroy, name='destroy'),
 ]

restful_products/semi_restful/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^products/', include('apps.products.urls', namespace='products')),
]

restful_products/apps/products/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class ProductManager(models.Manager):
    def create_new_product(self, request):
        self.create(name=request.POST['name'], description=request.POST['description'], price=request.POST['price'])

    def update_product(self, request, id):
        catz = self.filter(id=id).update(name=request.POST['name'], description=request.POST['description'], price=request.POST['price'])

    def destroy(self, request):
        pass


class Product(models.Model):
    name = models.CharField(max_length = 50)
    description = models.CharField(max_length = 100)
    price = models.DecimalField(max_digits=19, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = ProductManager()

restful_products/apps/products/views.py
from django.shortcuts import render, HttpResponse, redirect
from models import Product
  # Create your views here.
def index(request):
    context = {
        'products': Product.objects.all()[::-1]
    }

    return render(request, "products/index.html", context)

def show(request, id):
    context = {
        'product': Product.objects.get(id=id)
    }

    return render(request, "products/show.html", context)

def new(request):

    return render(request, "products/new.html")

def edit(request, id):
    context = {
        'product': Product.objects.get(id=id)
    }

    return render(request, "products/edit.html", context)

def create(request):
    Product.objects.create_new_product(request)

    return redirect("products:index")

def update(request, id):
    Product.objects.update_product(request, id)

    return redirect("products:index")

def destroy(request):
    pass

restful_products/apps/products/templates/products/edit.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Edit Products</title>
</head>

<body>
    <h1>Edit Product</h1>
    <form action="{% url 'products:update' product.id %}" method="post">
        {% csrf_token %}
        <p>Name: <input type="text" name="name" value="{{ product.name }}"></p>
        <p>Description: <input type="text" name="description" value="{{ product.description }}"></p>
        <p>Price: <input type="number" name="price" value="{{ product.price }}"></p>
        <input type="submit" name="submit" value="Update">
    </form>
    <a href="/products">Back</a>
</body>

</html>

restful_products/apps/products/templates/products/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <h1>Products</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
        {% for product in products%}
        <tr>
            <td>{{ product.name }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.price }}</td>
            <td><a href="{% url 'products:show' product.id %}">Show</a></td>
            <td><a href="{% url 'products:edit' product.id %}">Edit</a></td>
            <td><a href="{% url 'products:destroy' product.id %}">Remove</a></td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url 'products:new' %}">Add a new product</a>
</body>

</html>

restful_products/apps/products/templates/products/new.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>New Products</title>
</head>

<body>
    <h1>Add new products Here</h1>
    <form action="{% url 'products:create' %}" method="post">
        {% csrf_token %}
        <p>Name: <input type="text" name="name"></p>
        <p>Description: <input type="text" name="description"></p>
        <p>Price: <input type="number" name="price"></p>
        <input type="submit" name="submit" value="create">
    </form>
    <a href="/products">Back</a>
</body>

</html>

restful_products/apps/products/templates/products/show.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Show Products</title>
</head>

<body>
    <h1>Product {{ product.id }}</h1>
    <p>Name: {{ product.name }}</p>
    <p>Description: {{ product.description }}</p>
    <p>Price: {{ product.price }}</p>
    <a href="{% url 'products:edit' product.id %}">Edit</a>
    <a href="/products">Back</a>
</body>

</html>